### PR TITLE
Added ODF 4.8 templates

### PR DESCRIPTION
**Pull request by Shirisha-S-Rao-1**
Added ODF 4.8
Added metro classes for ODF 4.8
Updated image for 4.7 templates
Removed `container-private-endpoint` parameter

### CODE REVIEW

**Comment by Shirisha-S-Rao-1** [comment]
Tested the changes

Configuration :

```
% ibmcloud sat storage config get --config odf-local-4.8
Getting Satellite storage configuration details...
OK
                       
Name:               odf-local-4.8   
ID:                 8ab7b809-2d46-45e1-bbcb-89ec4d5d9538   
Template Name:      odf-local   
Template Version:   4.8   
Location:           c6bkjvqd0d4o7ad8h49g   

Configuration Parameters
Name                 Value   
billing-type         advanced   
cluster-encryption   false   
mon-device-path      /dev/disk/by-id/virtio-0717-11370d23-7968-4,/dev/disk/by-id/virtio-0727-0a22337e-fa48-4,/dev/disk/by-id/virtio-0737-4df951d5-1dc9-4   
num-of-osd           1   
ocs-cluster-name     ocscluster-auto   
odf-upgrade          false   
osd-device-path      /dev/disk/by-id/virtio-0717-d7c422c5-218c-4,/dev/disk/by-id/virtio-0727-4d56e19b-5b30-4,/dev/disk/by-id/virtio-0737-eb98f6d0-6473-4   

Secret Parameters
Name          Value   
iam-api-key   *****   

Storage Class Parameters
Storage Class Name           Parameter Name                                          Parameter Value   
sat-ocs-cephrbd-gold         allowVolumeExpansion                                    true   
                             clusterID                                               openshift-storage   
                             csi.storage.k8s.io/controller-expand-secret-name        rook-csi-rbd-provisioner   
                             csi.storage.k8s.io/controller-expand-secret-namespace   openshift-storage   
                             csi.storage.k8s.io/fstype                               ext4   
                             csi.storage.k8s.io/node-stage-secret-name               rook-csi-rbd-node   
                             csi.storage.k8s.io/node-stage-secret-namespace          openshift-storage   
                             csi.storage.k8s.io/provisioner-secret-name              rook-csi-rbd-provisioner   
                             csi.storage.k8s.io/provisioner-secret-namespace         openshift-storage   
                             imageFeatures                                           layering   
                             imageFormat                                             2   
                             pool                                                    ocs-storagecluster-cephblockpool   
                             provisioner                                             openshift-storage.rbd.csi.ceph.com   
                             reclaimPolicy                                           Delete   
                             storageclass.kubernetes.io/is-default-class             false   
                             volumeBindingMode                                       Immediate   
                                                                                        
sat-ocs-cephfs-gold          allowVolumeExpansion                                    true   
                             clusterID                                               openshift-storage   
                             csi.storage.k8s.io/controller-expand-secret-name        rook-csi-cephfs-provisioner   
                             csi.storage.k8s.io/controller-expand-secret-namespace   openshift-storage   
                             csi.storage.k8s.io/node-stage-secret-name               rook-csi-cephfs-node   
                             csi.storage.k8s.io/node-stage-secret-namespace          openshift-storage   
                             csi.storage.k8s.io/provisioner-secret-name              rook-csi-cephfs-provisioner   
                             csi.storage.k8s.io/provisioner-secret-namespace         openshift-storage   
                             fsName                                                  ocs-storagecluster-cephfilesystem   
                             provisioner                                             openshift-storage.cephfs.csi.ceph.com   
                             reclaimPolicy                                           Delete   
                             storageclass.kubernetes.io/is-default-class             false   
                             volumeBindingMode                                       Immediate   
                                                                                        
sat-ocs-cephrgw-gold         objectStoreName                                         ocs-storagecluster-cephobjectstore   
                             objectStoreNamespace                                    openshift-storage   
                             provisioner                                             openshift-storage.ceph.rook.io/bucket   
                             reclaimPolicy                                           Delete   
                             region                                                  us-east-1   
                             storageclass.kubernetes.io/is-default-class             false   
                             volumeBindingMode                                       Immediate   
                                                                                        
sat-ocs-noobaa-gold          bucketclass                                             noobaa-default-bucket-class   
                             provisioner                                             openshift-storage.noobaa.io/obc   
                             reclaimPolicy                                           Delete   
                             storageclass.kubernetes.io/is-default-class             false   
                             volumeBindingMode                                       Immediate   
                                                                                        
sat-ocs-cephrbd-gold-metro   allowVolumeExpansion                                    true   
                             clusterID                                               openshift-storage   
                             csi.storage.k8s.io/controller-expand-secret-name        rook-csi-rbd-provisioner   
                             csi.storage.k8s.io/controller-expand-secret-namespace   openshift-storage   
                             csi.storage.k8s.io/fstype                               ext4   
                             csi.storage.k8s.io/node-stage-secret-name               rook-csi-rbd-node   
                             csi.storage.k8s.io/node-stage-secret-namespace          openshift-storage   
                             csi.storage.k8s.io/provisioner-secret-name              rook-csi-rbd-provisioner   
                             csi.storage.k8s.io/provisioner-secret-namespace         openshift-storage   
                             imageFeatures                                           layering   
                             imageFormat                                             2   
                             pool                                                    ocs-storagecluster-cephblockpool   
                             provisioner                                             openshift-storage.rbd.csi.ceph.com   
                             reclaimPolicy                                           Delete   
                             storageclass.kubernetes.io/is-default-class             false   
                             volumeBindingMode                                       WaitForFirstConsumer   
                                                                                        
sat-ocs-cephfs-gold-metro    allowVolumeExpansion                                    true   
                             clusterID                                               openshift-storage   
                             csi.storage.k8s.io/controller-expand-secret-name        rook-csi-cephfs-provisioner   
                             csi.storage.k8s.io/controller-expand-secret-namespace   openshift-storage   
                             csi.storage.k8s.io/node-stage-secret-name               rook-csi-cephfs-node   
                             csi.storage.k8s.io/node-stage-secret-namespace          openshift-storage   
                             csi.storage.k8s.io/provisioner-secret-name              rook-csi-cephfs-provisioner   
                             csi.storage.k8s.io/provisioner-secret-namespace         openshift-storage   
                             fsName                                                  ocs-storagecluster-cephfilesystem   
                             provisioner                                             openshift-storage.cephfs.csi.ceph.com   
                             reclaimPolicy                                           Delete   
                             storageclass.kubernetes.io/is-default-class             false   
                             volumeBindingMode                                       WaitForFirstConsumer   
```

**Comment by Shirisha-S-Rao-1** [comment]
Controller pod 
```
% oc get pods -n kube-system | grep ocs                     
NAME                                                   READY   STATUS    RESTARTS   AGE
ibm-ocs-operator-controller-manager-55fc75c755-twgbc   1/1     Running   0          64s
```

**Comment by Shirisha-S-Rao-1** [comment]
Storagecluster 
```
% oc get storagecluster -n openshift-storage        
NAME                 AGE     PHASE   EXTERNAL   CREATED AT             VERSION
ocs-storagecluster   5m18s   Ready              2021-11-19T10:13:32Z   4.8.0
```

**Comment by Shirisha-S-Rao-1** [comment]
CSV :
```
% oc get csv -n openshift-storage
NAME                  DISPLAY                       VERSION   REPLACES              PHASE
ocs-operator.v4.8.4   OpenShift Container Storage   4.8.4     ocs-operator.v4.8.3   Succeeded
```

**Comment by Shirisha-S-Rao-1** [comment]
ODF pods 
```
% oc get pods -n openshift-storage
NAME                                                              READY   STATUS      RESTARTS   AGE
csi-cephfsplugin-2dkjn                                            3/3     Running     0          4m58s
csi-cephfsplugin-kcv8h                                            3/3     Running     0          4m58s
csi-cephfsplugin-provisioner-84964c8df5-gz9mf                     6/6     Running     0          4m58s
csi-cephfsplugin-provisioner-84964c8df5-mxfnj                     6/6     Running     0          4m58s
csi-cephfsplugin-qkmwx                                            3/3     Running     0          4m58s
csi-rbdplugin-9gdqc                                               3/3     Running     0          4m59s
csi-rbdplugin-pndmr                                               3/3     Running     0          4m59s
csi-rbdplugin-provisioner-6466fc8bf6-92b7h                        6/6     Running     0          4m59s
csi-rbdplugin-provisioner-6466fc8bf6-jw8dj                        6/6     Running     0          4m59s
csi-rbdplugin-t8m8w                                               3/3     Running     0          4m59s
noobaa-core-0                                                     1/1     Running     0          3m6s
noobaa-db-pg-0                                                    1/1     Running     0          3m6s
noobaa-endpoint-54d58466cd-5kbxz                                  1/1     Running     0          87s
noobaa-operator-66b487b679-rlqn4                                  1/1     Running     0          5m37s
ocs-metrics-exporter-9cf6d7f54-5qbhd                              1/1     Running     0          5m36s
ocs-operator-648946bb-zxd4n                                       1/1     Running     0          5m37s
rook-ceph-crashcollector-sat-odf-workernode01-7f75cb9b64-fklrz    1/1     Running     0          2m46s
rook-ceph-crashcollector-sat-odf-workernode02-69d8ff85c5-wpwh6    1/1     Running     0          2m4s
rook-ceph-crashcollector-sat-odf-workernode03-dd5554d6-b9bv9      1/1     Running     0          2m47s
rook-ceph-mds-ocs-storagecluster-cephfilesystem-a-cd68b555r5scn   2/2     Running     0          2m47s
rook-ceph-mds-ocs-storagecluster-cephfilesystem-b-7b769864kvmq6   2/2     Running     0          2m46s
rook-ceph-mgr-a-654d8975d4-44wfw                                  2/2     Running     0          3m30s
rook-ceph-mon-a-6447954c75-xjbs6                                  2/2     Running     0          4m21s
rook-ceph-mon-b-65cd86d769-mhdgm                                  2/2     Running     0          3m57s
rook-ceph-mon-c-64bd4854ff-t42wr                                  2/2     Running     0          3m43s
rook-ceph-operator-54cd89f569-6rbcv                               1/1     Running     0          5m37s
rook-ceph-osd-0-7c9754d98-47qrg                                   2/2     Running     0          3m14s
rook-ceph-osd-1-79568c457c-xf7wl                                  2/2     Running     0          3m15s
rook-ceph-osd-2-6bd6c4b6c7-v94rm                                  2/2     Running     0          3m8s
rook-ceph-osd-prepare-ocs-deviceset-0-data-0pz6h2-dqn5f           0/1     Completed   0          3m24s
rook-ceph-osd-prepare-ocs-deviceset-1-data-0dzbw8-46d5r           0/1     Completed   0          3m24s
rook-ceph-osd-prepare-ocs-deviceset-2-data-0x755h-qckpt           0/1     Completed   0          3m24s
rook-ceph-rgw-ocs-storagecluster-cephobjectstore-a-7b789fbspv2b   2/2     Running     0          2m4s
```

**Comment by Shirisha-S-Rao-1** [comment]
Storageclasses 
```
% oc get sc
NAME                          PROVISIONER                             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
localblock                    kubernetes.io/no-provisioner            Delete          WaitForFirstConsumer   false                  5m48s
localfile                     kubernetes.io/no-provisioner            Delete          WaitForFirstConsumer   false                  5m49s
ocs-storagecluster-ceph-rbd   openshift-storage.rbd.csi.ceph.com      Delete          Immediate              true                   5m31s
ocs-storagecluster-ceph-rgw   openshift-storage.ceph.rook.io/bucket   Delete          Immediate              false                  5m31s
ocs-storagecluster-cephfs     openshift-storage.cephfs.csi.ceph.com   Delete          Immediate              true                   5m31s
openshift-storage.noobaa.io   openshift-storage.noobaa.io/obc         Delete          Immediate              false                  96s
sat-ocs-cephfs-gold           openshift-storage.cephfs.csi.ceph.com   Delete          Immediate              true                   6m54s
sat-ocs-cephfs-gold-metro     openshift-storage.cephfs.csi.ceph.com   Delete          WaitForFirstConsumer   true                   6m53s
sat-ocs-cephrbd-gold          openshift-storage.rbd.csi.ceph.com      Delete          Immediate              true                   6m55s
sat-ocs-cephrbd-gold-metro    openshift-storage.rbd.csi.ceph.com      Delete          WaitForFirstConsumer   true                   6m53s
sat-ocs-cephrgw-gold          openshift-storage.ceph.rook.io/bucket   Delete          Immediate              false                  6m54s
sat-ocs-noobaa-gold           openshift-storage.noobaa.io/obc         Delete          Immediate              false                  6m54s
```

**Comment by Shirisha-S-Rao-1** [comment]
Sample app creation tested with the metro classes

RBD :

```
% oc get pvc
NAME      STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS                 AGE
odf-pvc   Pending                                      sat-ocs-cephrbd-gold-metro   18s
% oc get pvc
NAME      STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS                 AGE
odf-pvc   Pending                                      sat-ocs-cephrbd-gold-metro   21s
% oc get pvc               
NAME       STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                 AGE
odf-pvc    Pending                                                                        sat-ocs-cephrbd-gold-metro   61s
odf-pvc1   Bound     pvc-ea81ca82-8268-4136-9f5e-58737904378d   10Gi       RWO            sat-ocs-cephrbd-gold         5s
% oc create -f sample-pod.yaml
pod/app created
% oc get pvc               
NAME       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                 AGE
odf-pvc    Bound    pvc-c56474d4-71fd-4a7d-ae69-863c4a97030a   10Gi       RWO            sat-ocs-cephrbd-gold-metro   112s
odf-pvc1   Bound    pvc-ea81ca82-8268-4136-9f5e-58737904378d   10Gi       RWO            sat-ocs-cephrbd-gold         56s
% oc get pods
NAME   READY   STATUS    RESTARTS   AGE
app    1/1     Running   0          27s
```

**Comment by Shirisha-S-Rao-1** [comment]
OCSCluster 

```
% oc describe ocscluster ocscluster-auto
Name:         ocscluster-auto
Namespace:    
Labels:       <none>
Annotations:  deploy.razee.io/last-applied-configuration:
                {"apiVersion":"ocs.ibm.io/v1","kind":"OcsCluster","metadata":{"name":"ocscluster-auto","namespace":"default"},"spec":{"monStorageClassName...
API Version:  ocs.ibm.io/v1
Kind:         OcsCluster
Metadata:
  Creation Timestamp:  2021-11-19T10:12:22Z
  Finalizers:
    finalizer.ocs.ibm.io
  Generation:  1
Spec:
  Billing Type:        advanced
  Cluster Encryption:  false
  Mon Device Paths:
    /dev/disk/by-id/virtio-0717-11370d23-7968-4
    /dev/disk/by-id/virtio-0727-0a22337e-fa48-4
    /dev/disk/by-id/virtio-0737-4df951d5-1dc9-4
  Mon Size:                1
  Mon Storage Class Name:  localfile
  Num Of Osd:              1
  Ocs Upgrade:             false
  Osd Device Paths:
    /dev/disk/by-id/virtio-0717-d7c422c5-218c-4
    /dev/disk/by-id/virtio-0727-4d56e19b-5b30-4
    /dev/disk/by-id/virtio-0737-eb98f6d0-6473-4
  Osd Size:                1
  Osd Storage Class Name:  localblock
Status:
  Storage Cluster Status:  Ready
Events:                    <none>
```

**Review by akgunjal — APPROVED** [review]
LGTM

**Pull request merged**
