### PR TITLE
Update the VDO docker image for vSphere CSI Driver Template

### PR DESCRIPTION
**Pull request by asifdxtreme**
Update the vdo docker image with fix for certificate validation for webhook.

### CODE REVIEW

**Review by gauravAggrhari — APPROVED** [review]
PR LGTM!

**Comment by gauravAggrhari** [comment]
Please update the sign-off also. The check is failing.

**Review by gauravAggrhari — APPROVED** [review]
PR LGTM!

**Review by mssachan — APPROVED** [review]
LGTM

**Pull request merged**
