### PR TITLE
Add README for storageclasses for AWS EBS

### PR DESCRIPTION
**Pull request by mssachan**

### CODE REVIEW

**Review by prgavali — CHANGES_REQUESTED** [review]
In case the resources are not created in the cluster, redirect to see the deplyment error 
1.  Get error from UI 
2. Get error from MustacheController error 
3. Contact support

**Comment by mssachan** [comment]
@prgavali we will have seperate runbook for checking deployment issues. I think we should keep this readme clean and simple.

**Comment by nkkashyap** [comment]
@prgavali @mssachan 
We need to create runbook to debug the deployment issues. 
The readme should contain the pre-reqs and steps to deploy the storage solution.

**Review by nkkashyap — APPROVED** [review]
looks good

**Review by prgavali — APPROVED** [review]
LGTM

**Pull request merged**
