### PR TITLE
Add PSA labels in the namespace created by Template

### PR DESCRIPTION
**Pull request by asifdxtreme**
Added the PSA labels in the template as the latest OC 4.12 has the PSA by default created to restricted mode.

### CODE REVIEW

**Comment by asifdxtreme** [comment]
@gauravAggrahari Can you please review and approve the PR so that we can get unblocked.

**Review by mssachan — APPROVED** [review]
lgtm

**Comment by asifdxtreme** [comment]
@gauravAggrahari since we have the approvals can we merge this now?

**Review by gauravAggrahari — APPROVED** [review]
PR LGTM!

**Comment by gauravAggrhari** [comment]
@asifdxtreme can you please test this Template and past e the results ?

**Pull request merged**
