### PR TITLE
add label pod-security.kubernetes.io/enforce: privileged to namespaces vmware-system-csi and vmware-system-vdo

### PR DESCRIPTION
**Pull request by gauravAggrahari**

### CODE REVIEW

**Review by Bhagyashreek8 — APPROVED** [review]

**Review by mssachan — CHANGES_REQUESTED** [review]
Update supported OCP versions field

**Review by nkkashyap — APPROVED** [review]
lgtm

**Review by mssachan — CHANGES_REQUESTED** [review]
Please update changelog.json as well and give release date as `9 May 2024`

**Review by mssachan — APPROVED** [review]
LGTM

**Pull request merged**
